apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git::https://github.com/openshift-pipelines/pipeline-service.git/developer/openshift/gitops/argocd/minio?ref=40eeb2ee7df776f3b6a9ff579055475c73007139
