apiVersion: batch/v1
kind: Job
metadata:
  name: minio-tenant-check
  namespace: tekton-results
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.12@sha256:9f0cdc00b1b1a3c17411e50653253b9f6bb5329ea4fb82ad983790a6dbf2d9ad
          command:
            - /bin/bash
            - -c
            - |
              printf "Waiting for minio tenant to be present";
              curl https://raw.githubusercontent.com/openshift-pipelines/pipeline-service/main/operator/images/cluster-setup/content/bin/utils.sh --output /tmp/utils.sh;

              source /tmp/utils.sh;
              check_pod_by_label tekton-results "app=minio"
          imagePullPolicy: Always
          name: minio-tenant-checker
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      backoffLimit: 5
      # terminationGracePeriodSeconds: 30
      serviceAccount: minio-tenant-checker
      serviceAccountName: minio-tenant-checker
