apiVersion: batch/v1
kind: Job
metadata:
  name: minio-tenant-check
  namespace: tekton-results
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.12@sha256:9f0cdc00b1b1a3c17411e50653253b9f6bb5329ea4fb82ad983790a6dbf2d9ad
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for minio tenant to be present";
              oc get pods -n tekton-results;
              numOfAttempts=40;
              ns=tekton-results;
              i=0;
              
              while [ -z "$(oc get pods -l app=minio -n $ns --no-headers -o custom-columns=':metadata.name')" ]; do
                printf '.';
                sleep 5;
                i=$((i+1));
                if [[ $i -eq "${numOfAttempts}" ]]; then
                  printf "\n[ERROR] Pod %s not found by timeout \n" "app=minio" >&2;
                  oc -n "$ns" get events | grep Warning;
                  exit 1;
                fi
              done
          imagePullPolicy: Always
          name: minio-tenant-checker
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      # terminationGracePeriodSeconds: 30
      serviceAccount: minio-tenant-checker
      serviceAccountName: minio-tenant-checker
