apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio-storage
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/minio
                environment: development
                clusterDir: ""
          - list:
              elements:
                - nameNormalized: stone-stg-m01
                  values.clusterDir: stone-stg-m01
                - nameNormalized: stone-stg-rh01
                  values.clusterDir: stone-stg-rh01
  template:
    metadata:
      name: minio-storage-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/cloud-eda/infra-deployments.git
        targetRevision: main
      destination:
        namespace: default
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
