apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-application-sets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: argo-cd-apps/overlays/staging
    repoURL: https://github.com/cloud-eda/infra-deployments.git
    targetRevision: integrate-minio-storage
  destination:
    namespace: argocd-staging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
